services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev
    networks:
      - concourse-net

  concourse-db:
    image: postgres:13
    container_name: concourse-db
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: ${CONC_PASS}
    networks:
      - concourse-net

  concourse:
    image: concourse/concourse:7.9
    container_name: concourse
    command: quickstart
    privileged: true
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: ${CONC_PASS}
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: "http://localhost:8080"
      CONCOURSE_VAULT_URL: "http://vault:8200"
      CONCOURSE_VAULT_AUTH_BACKEND: token
      CONCOURSE_VAULT_TOKEN: "root-token"
      CONCOURSE_VAULT_PATH: "secret"
      CONCOURSE_ADD_LOCAL_USER: "test:test"
      CONCOURSE_MAIN_TEAM_LOCAL_USER: "test"
    depends_on:
      - vault
      - concourse-db
    networks:
      - concourse-net

networks:
  concourse-net:
    driver: bridge

volumes:
  concourse-db-data:
